# Generated by Django 6.0.4 on 2026-04-18 03:23

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('tipo', models.CharField(choices=[('helado_cuarto', 'Helado 1/4 kg'), ('helado_medio', 'Helado 1/2 kg'), ('helado_kilo', 'Helado 1 kg'), ('postre', 'Postre')], max_length=20)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('descripcion', models.TextField(blank=True)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Productos',
                'ordering': ['tipo', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='Sabor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('stock_kg', models.DecimalField(decimal_places=3, default=0, max_digits=8, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('stock_minimo_kg', models.DecimalField(decimal_places=3, default=Decimal('0.5'), help_text='Si el stock cae por debajo de este valor, se muestra como agotado en la web.', max_digits=8)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Sabor',
                'verbose_name_plural': 'Sabores',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Topping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('precio_extra', models.DecimalField(decimal_places=2, default=Decimal('100.00'), help_text='Precio adicional a partir del segundo topping.', max_digits=8)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Topping',
                'verbose_name_plural': 'Toppings',
                'ordering': ['nombre'],
            },
        ),
    ]
