# Generated by Django 6.0.4 on 2026-04-18 21:38

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InsumoStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('unidad', models.CharField(choices=[('unidad', 'Unidad'), ('paquete', 'Paquete')], default='unidad', max_length=15)),
                ('cantidad_actual', models.PositiveIntegerField(default=0)),
                ('cantidad_minima', models.PositiveIntegerField(default=10)),
            ],
            options={
                'verbose_name': 'Insumo',
                'verbose_name_plural': 'Insumos',
                'ordering': ['nombre'],
            },
        ),
        migrations.AddField(
            model_name='producto',
            name='stock_minimo_u',
            field=models.PositiveIntegerField(default=5),
        ),
        migrations.AddField(
            model_name='producto',
            name='stock_unidades',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='producto',
            name='tiene_stock',
            field=models.BooleanField(default=False, help_text='Si está activo, se controla el stock de unidades.'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='tipo',
            field=models.CharField(choices=[('helado_cuarto', 'Helado 1/4 kg'), ('helado_medio', 'Helado 1/2 kg'), ('helado_kilo', 'Helado 1 kg'), ('postre', 'Postre'), ('otro', 'Otro')], max_length=20),
        ),
        migrations.AlterField(
            model_name='sabor',
            name='stock_minimo_kg',
            field=models.DecimalField(decimal_places=3, default=Decimal('0.5'), max_digits=8),
        ),
        migrations.AlterField(
            model_name='topping',
            name='precio_extra',
            field=models.DecimalField(decimal_places=2, default=Decimal('100.00'), max_digits=8),
        ),
        migrations.AddField(
            model_name='producto',
            name='insumo_asociado',
            field=models.ForeignKey(blank=True, help_text='Insumo que se descuenta 1 unidad por cada ítem vendido (ej: térmico 1/4).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='productos', to='productos.insumostock'),
        ),
    ]
