# Generated by Django 6.0.4 on 2026-04-18 03:23

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('productos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(editable=False, max_length=10, unique=True)),
                ('cliente_nombre', models.CharField(max_length=150)),
                ('cliente_telefono', models.CharField(max_length=30)),
                ('tipo_pedido', models.CharField(choices=[('WEB', 'Web'), ('MOSTRADOR', 'Mostrador')], default='WEB', max_length=15)),
                ('tipo_entrega', models.CharField(choices=[('RETIRO', 'Retiro en local'), ('DELIVERY', 'Delivery')], default='RETIRO', max_length=10)),
                ('direccion_entrega', models.CharField(blank=True, max_length=255)),
                ('estado', models.CharField(choices=[('RECIBIDO', 'Recibido'), ('EN_PREPARACION', 'En preparación'), ('LISTO', 'Listo'), ('EN_CAMINO', 'En camino'), ('ENTREGADO', 'Entregado'), ('CANCELADO', 'Cancelado')], default='RECIBIDO', max_length=15)),
                ('metodo_pago_principal', models.CharField(choices=[('EFECTIVO', 'Efectivo'), ('MERCADOPAGO', 'MercadoPago'), ('MIXTO', 'Mixto')], default='EFECTIVO', max_length=15)),
                ('total', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('comentarios', models.TextField(blank=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Pedido',
                'verbose_name_plural': 'Pedidos',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='ItemPedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField(default=1)),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('subtotal', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('comentarios', models.TextField(blank=True, help_text='Ej: más chocolate que vainilla, sin toppings, etc.')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='items_pedido', to='productos.producto')),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='pedidos.pedido')),
            ],
            options={
                'verbose_name': 'Ítem de pedido',
                'verbose_name_plural': 'Ítems de pedido',
            },
        ),
        migrations.CreateModel(
            name='ItemPedidoSabor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orden', models.PositiveSmallIntegerField(default=0)),
                ('item_pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sabores', to='pedidos.itempedido')),
                ('sabor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='apariciones', to='productos.sabor')),
            ],
            options={
                'verbose_name': 'Sabor de ítem',
                'verbose_name_plural': 'Sabores de ítem',
                'ordering': ['orden'],
            },
        ),
        migrations.CreateModel(
            name='ItemPedidoTopping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='toppings', to='pedidos.itempedido')),
                ('topping', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='apariciones', to='productos.topping')),
            ],
            options={
                'verbose_name': 'Topping de ítem',
                'verbose_name_plural': 'Toppings de ítem',
                'unique_together': {('item_pedido', 'topping')},
            },
        ),
    ]
