# Generated by Django 6.0.4 on 2026-04-18 21:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0001_initial'),
        ('productos', '0002_insumostock_producto_stock_minimo_u_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itempedido',
            name='producto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='items_pedido', to='productos.producto'),
        ),
    ]
