# Generated by Django 6.0.4 on 2026-04-21 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pago',
            name='referencia_externa',
        ),
        migrations.AddField(
            model_name='pago',
            name='referencia',
            field=models.CharField(blank=True, help_text='Nro. de comprobante, ID de transacción MP, etc. No aplica a efectivo.', max_length=200),
        ),
        migrations.AddField(
            model_name='pago',
            name='subtipo',
            field=models.CharField(blank=True, choices=[('DEBITO', 'Débito'), ('CREDITO', 'Crédito'), ('MERCADOPAGO', 'MercadoPago'), ('TRANSFERENCIA', 'Transferencia')], default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='pago',
            name='estado',
            field=models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('APROBADO', 'Aprobado'), ('RECHAZADO', 'Rechazado')], default='APROBADO', max_length=12),
        ),
        migrations.AlterField(
            model_name='pago',
            name='tipo',
            field=models.CharField(choices=[('EFECTIVO', 'Efectivo'), ('TARJETA', 'Tarjeta'), ('DIGITAL', 'Digital')], max_length=15),
        ),
    ]
