# Generated by Django 6.0.4 on 2026-04-26 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagos', '0003_caja_cajasesion_movimientocajasesion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cajasesion',
            name='fondo_fijo_dejado',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Monto de efectivo dejado para la siguiente sesión al cerrar.', max_digits=12, null=True),
        ),
    ]
